export * from "./use-admin-applications";
export * from "./use-admin-courses";
export * from "./use-admin-schools";
export * from "./use-admin-sync";
export * from "./use-admin-system";
export * from "./use-admin-telegram";
export * from "./use-admin-templates";
export * from "./use-admin-rejection-reasons";
export * from "./use-admin-managers";
